// PostgreSQL-backed persistence (replaces file-based store)
import 'server-only';

export {
  MVP_REQUIRED_FRAMEWORKS,
  getOrganizationName,
  setOrganizationName,
  getActivatedFrameworkIds,
  getActivations,
  activateFramework,
  deactivateFramework,
  isMvpRequiredFramework,
  getControlCompliance,
  getControlComplianceBatch,
  updateControlCompliance,
  getControlRemediation,
  updateControlRemediation,
  getControlIssues,
  getOpenIssueCountByControlIds,
  createControlIssue,
  updateControlIssue,
  deleteControlIssue,
  getControlEvidence,
  getControlEvidenceById,
  hasControlEvidenceForContext,
  getControlIdsWithEvidenceForContext,
  createControlEvidence,
  deleteControlEvidence,
  getRisks,
  getRisksByControlId,
  getOpenRiskCountByControlIds,
  getRiskById,
  createRisk,
  updateRisk,
  deleteRisk,
  getRiskRegister,
  getAllControlIssuesForOrg,
  getDashboardSummary,
  getExecutiveDashboard,
  createDefaultAccessConnections,
  createDefaultCompliance,
} from './db/repository';
