import type { AssuranceSource, AssuranceVulnerability } from '@/lib/assurance/types';

/** Demo / fallback browse host — live tickets use JIRA_BASE_URL from env. */
const DEMO_JIRA_BROWSE =
  (process.env.JIRA_BASE_URL?.trim().replace(/\/$/, '') ||
    process.env.NEXT_PUBLIC_JIRA_BASE_URL?.trim().replace(/\/$/, '') ||
    'https://propelreadysolutions.atlassian.net') + '/browse';

function demoBrowseUrl(key: string): string {
  return `${DEMO_JIRA_BROWSE}/${key}`;
}

/**
 * Sample open vulnerabilities for localhost when Jira is not configured.
 * Always marked demo: true — never presented as live Jira sync.
 */
export const DEMO_OPEN_VULNERABILITIES: AssuranceVulnerability[] = [
  {
    id: 'demo-sast-001',
    key: 'SEC-1901',
    summary: '[SAST] Hardcoded AWS access key in payment-service config',
    status: 'To Do',
    severity: 'critical',
    priority: 'Highest',
    source: 'sast',
    createdAt: '2026-07-08T10:00:00.000Z',
    updatedAt: '2026-07-12T09:00:00.000Z',
    url: demoBrowseUrl('SEC-1901'),
    assignee: 'AppSec Squad',
    labels: ['sast', 'secrets'],
    demo: true,
  },
  {
    id: 'demo-sast-002',
    key: 'SEC-1902',
    summary: '[SAST] SQL string concatenation in OrderRepository.findByFilter',
    status: 'In Progress',
    severity: 'high',
    priority: 'High',
    source: 'sast',
    createdAt: '2026-07-05T14:20:00.000Z',
    updatedAt: '2026-07-11T16:30:00.000Z',
    url: demoBrowseUrl('SEC-1902'),
    assignee: 'Backend Platform',
    labels: ['sast', 'injection'],
    demo: true,
  },
  {
    id: 'demo-sast-003',
    key: 'SEC-1895',
    summary: '[SAST] Insecure deserialization of user-controlled JSON (Jackson)',
    status: 'To Do',
    severity: 'high',
    priority: 'High',
    source: 'sast',
    createdAt: '2026-06-28T11:00:00.000Z',
    updatedAt: '2026-07-10T08:15:00.000Z',
    url: demoBrowseUrl('SEC-1895'),
    assignee: 'AppSec Squad',
    labels: ['sast'],
    demo: true,
  },
  {
    id: 'demo-dast-001',
    key: 'SEC-1859',
    summary: '[DAST] Fix SQL injection in Customer Portal search API',
    status: 'In Progress',
    severity: 'critical',
    priority: 'Highest',
    source: 'dast',
    createdAt: '2026-06-29T09:00:00.000Z',
    updatedAt: '2026-07-03T12:00:00.000Z',
    url: demoBrowseUrl('SEC-1859'),
    assignee: 'AppSec Squad',
    labels: ['dast'],
    demo: true,
  },
  {
    id: 'demo-dast-002',
    key: 'SEC-1847',
    summary: '[DAST] IDOR on Document Hub file download endpoint',
    status: 'In Review',
    severity: 'high',
    priority: 'High',
    source: 'dast',
    createdAt: '2026-06-21T10:00:00.000Z',
    updatedAt: '2026-07-01T15:00:00.000Z',
    url: demoBrowseUrl('SEC-1847'),
    assignee: 'Document Hub Team',
    labels: ['dast'],
    demo: true,
  },
  {
    id: 'demo-dast-003',
    key: 'SEC-1844',
    summary: '[DAST] Sanitize reflected XSS in Admin Console login error',
    status: 'To Do',
    severity: 'high',
    priority: 'High',
    source: 'dast',
    createdAt: '2026-06-19T08:00:00.000Z',
    updatedAt: '2026-06-19T08:00:00.000Z',
    url: demoBrowseUrl('SEC-1844'),
    assignee: 'Admin Console Team',
    labels: ['dast'],
    demo: true,
  },
  {
    id: 'demo-infra-001',
    key: 'SEC-1856',
    summary: '[VM] Patch Next.js middleware bypass on prod web cluster',
    status: 'To Do',
    severity: 'critical',
    priority: 'Highest',
    source: 'infra',
    createdAt: '2026-07-02T10:00:00.000Z',
    updatedAt: '2026-07-02T10:00:00.000Z',
    url: demoBrowseUrl('SEC-1856'),
    assignee: 'Web Platform',
    labels: ['infra', 'vm'],
    demo: true,
  },
  {
    id: 'demo-infra-002',
    key: 'SEC-1842',
    summary: '[VM] Upgrade OpenSSH on prod-api-01 (regreSSHion)',
    status: 'In Progress',
    severity: 'critical',
    priority: 'Highest',
    source: 'infra',
    createdAt: '2026-03-13T09:00:00.000Z',
    updatedAt: '2026-07-04T11:00:00.000Z',
    url: demoBrowseUrl('SEC-1842'),
    assignee: 'Infrastructure Ops',
    labels: ['infra'],
    demo: true,
  },
  {
    id: 'demo-infra-003',
    key: 'SEC-1798',
    summary: '[VM] Apply Kerberos PAC validation patch on AD DC',
    status: 'In Progress',
    severity: 'high',
    priority: 'High',
    source: 'infra',
    createdAt: '2026-02-19T10:00:00.000Z',
    updatedAt: '2026-06-30T14:00:00.000Z',
    url: demoBrowseUrl('SEC-1798'),
    assignee: 'Identity Team',
    labels: ['infrastructure'],
    demo: true,
  },
  {
    id: 'demo-cloud-001',
    key: 'SEC-1910',
    summary: '[CLOUD] Public S3 bucket allowing unauthenticated list/get',
    status: 'To Do',
    severity: 'critical',
    priority: 'Highest',
    source: 'cloud',
    createdAt: '2026-07-09T07:30:00.000Z',
    updatedAt: '2026-07-12T10:00:00.000Z',
    url: demoBrowseUrl('SEC-1910'),
    assignee: 'Cloud Security',
    labels: ['cloud', 'cspm'],
    demo: true,
  },
  {
    id: 'demo-cloud-002',
    key: 'SEC-1908',
    summary: '[CLOUD] Security group 0.0.0.0/0 on RDP (3389) in prod VPC',
    status: 'In Progress',
    severity: 'high',
    priority: 'High',
    source: 'cloud',
    createdAt: '2026-07-07T12:00:00.000Z',
    updatedAt: '2026-07-11T09:45:00.000Z',
    url: demoBrowseUrl('SEC-1908'),
    assignee: 'Network Security',
    labels: ['cloud'],
    demo: true,
  },
  {
    id: 'demo-cloud-003',
    key: 'SEC-1904',
    summary: '[CLOUD] IAM user with AdminAccess and no MFA enforced',
    status: 'To Do',
    severity: 'high',
    priority: 'High',
    source: 'cloud',
    createdAt: '2026-07-01T16:00:00.000Z',
    updatedAt: '2026-07-08T11:20:00.000Z',
    url: demoBrowseUrl('SEC-1904'),
    assignee: 'Identity Team',
    labels: ['cloud', 'iam'],
    demo: true,
  },
];

export function getDemoVulnerabilities(
  source: AssuranceSource | 'all' = 'all'
): AssuranceVulnerability[] {
  if (source === 'all') return [...DEMO_OPEN_VULNERABILITIES];
  return DEMO_OPEN_VULNERABILITIES.filter((v) => v.source === source);
}
